### ISSUE TITLE
疑问：现实情况是：在判断没有开启自启动权限的时候，才提示用户。

### ISSUE THREAD

**Issue by caprice** [HLQ-Struggle/SkipSelfStartManager#1]
如题：怎样才能知道有没有开启自启动权限呢？

**Comment by HLQ-Struggle** [comment]
嗯，是啊。其实有关这块内容，是当初做监听开机启动广播时了解的，当初了解到如果某个App获取自启动权限后才能监听到，否则是监听不到的。所以直接在监听开机启动的时候来状态标识即可。
